apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce
spec:
  selector:
    matchLabels:
      run: ecommerce
  replicas: 1
  template:
    metadata:
      labels:
        run: ecommerce
    spec:
      containers:
      - name: ecommerce
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 80
